### ISSUE TITLE
Vectorization: Make behaviour clear and work the same everywhere

### ISSUE THREAD

**Issue by stefanheyder** [geomstats/geomstats#338] opened 2020-01-17 09:39 UTC
Currently, vectorization is handled differently by different functions (and backends); the behaviour should be uniform across all of geomstats. Suppose we have a function
```
foo(bar, baz)
```
where `foo` is vectorized over both `bar` and `baz`, `bar` being arrays of the same shape s and `foo` returns an array of shape r. We should be able to handle the following cases:

### bar and baz are of shape s (e.g. only one object passed for each argument)
`foo(bar, baz)` is of shape r
### bar is of shape (n, s) and baz is of shape s
`foo(bar, baz)` should be of shape (n,r) where each of the r-arrays is the result of applying `foo` pointwise to bar.
### bar is of shape s and baz is of shape (n,s)
Same as above
### bar is of shape (n,s) and baz is of shape (n,s)
`foo(bar, baz)` should be of shape (n,r), applying `foo` across the first dimension: the first element of the output is the result of `foo(bar[0], baz[0])`, the second `foo(bar[1], baz[1])` and so on.

@cshewmake2 suggested adding a decorator function doing the following:
Remember the shape of the input arrays, cast them using `to_ndarray` to have shape (n,s) (even if n = 1), calculate the function result and cast back to the desired shape.

This would allow the developers to focus on vectorized functions, not having to worry about casting between arrays of different shape. It might also be useful to have a look at numpy, as their functions implement exactly this behaviour.

**Comment by ninamiolane** [comment] 2020-01-17 13:00
Some documentation on how NumPy does it: https://docs.scipy.org/doc/numpy/reference/internals.code-explanations.html#broadcasting

And C code:
https://github.com/numpy/numpy/blob/f31ce546045ccb765ef0992b9c841d4682eee775/numpy/core/src/multiarray/iterators.c#L1162

**Comment by ninamiolane** [comment] 2020-01-20 06:24
Duplicate of issue #48, I am closing #48

**Comment by ninamiolane** [comment] 2020-01-20 06:29
Update w.r.t. #128, closing #128

**Comment by ninamiolane** [comment] 2020-04-14 21:35
The two main problems of this issue are:
- **a.** Functions output unintuitive shapes: 
    - e.g. `gs.inner_product([1, 2, 3], [1, 1, 1]) == gs.array([[6]])` instead of `gs.array(6)`,
- **b.** Many reshapings happen in the codebase, with `gs.to_ndarray`, which:
    - **b1:** slows it down,
    - **b2:** make the code less readable.

I started to address these, with the following strategy:
**1.** Use a decorator implemented in `vectorization.py`:
    - Pros: This addresses **a**, 
    - Cons: This does not necessarily address **b1** nor **b2**.
**2.** Generalize the behavior of `einsum`/`swapaxes` or the use of `-1` and `-2` indices for tf and pytorch, so that it matches np's and become more flexible.
    - Pros: This addresses **a**, **b1** and **b2**, 
    - Cons: Refactorizing all the codebase this way takes a lot of time, and we would like to have the consistent behavior **a** everywhere asap.

Therefore, in the PRs related to this issue, I choose to:
- Use **2** whenever possible,
- Use **1** in the case where changing the code was too time-consuming, in order to at least address **a** everywhere in the codebase.

Any thoughts on this? @nguigs @nkoep

**Closed** 2021-12-15 17:49 UTC
Labels: refactoring, high priority
